
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.ariel-os]
url = "https://raw.githubusercontent.com/ariel-os/ariel-os/main/supply-chain/audits.toml"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.git-broom]
audit-as-crates-io = true

[[exemptions.anyhow]]
version = "1.0.102"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.cassowary]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.castaway]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.compact_str]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.crossterm]]
version = "0.28.1"
criteria = "safe-to-deploy"

[[exemptions.crossterm_winapi]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.4.1"
criteria = "safe-to-run"

[[exemptions.git-broom]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.17.0"
criteria = "safe-to-run"

[[exemptions.id-arena]]
version = "2.3.0"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.14.0"
criteria = "safe-to-run"

[[exemptions.indoc]]
version = "2.0.7"
criteria = "safe-to-deploy"

[[exemptions.instability]]
version = "0.3.12"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.184"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.lru]]
version = "0.12.5"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.5"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.12"
criteria = "safe-to-deploy"

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.prettyplease]]
version = "0.2.37"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.45"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "6.0.0"
criteria = "safe-to-run"

[[exemptions.ratatui]]
version = "0.29.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.149"
criteria = "safe-to-deploy"

[[exemptions.signal-hook]]
version = "0.3.18"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-mio]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.8"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.unicode-segmentation]]
version = "1.13.2"
criteria = "safe-to-deploy"

[[exemptions.unicode-truncate]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.zmij]]
version = "1.0.21"
criteria = "safe-to-deploy"
